<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>{{ $profile['name'] }} - Resume</title>
<style>
@page{margin:36pt 40pt 38pt}body{font-family:'DejaVu Sans',sans-serif;font-size:9pt;line-height:1.5;color:#232b35}h1{font-size:23pt;letter-spacing:-.7pt;line-height:1.1;margin:0 0 7pt;color:#182943}a{color:#2948a3;text-decoration:none}.headline{font-size:11pt;color:#2948a3;margin:0 0 10pt}.contact{font-size:8pt;line-height:1.65;color:#465062;border-bottom:1pt solid #243c62;padding-bottom:13pt;margin-bottom:15pt}h2{font-size:9pt;letter-spacing:1pt;text-transform:uppercase;color:#2948a3;margin:17pt 0 8pt;border-bottom:.5pt solid #d4dbe5;padding-bottom:4pt;page-break-after:avoid}h3{font-size:9.5pt;margin:0 0 2pt;line-height:1.4}p{margin:0 0 6pt}.entry{margin-bottom:10pt;page-break-inside:avoid}.meta{font-size:8pt;color:#5d6571;margin-bottom:4pt}.skill{margin-bottom:3pt}.date{float:right;font-size:8pt;font-weight:normal;color:#4b5460}.footer{position:fixed;bottom:-21pt;left:0;right:0;font-size:7pt;color:#88909a}.footer .page:after{content:counter(page)}.footer .page{float:right}.summary{line-height:1.6}
</style></head><body>
<div class="footer">{{ $profile['name'] }} | Laravel & Full Stack Developer <span class="page"></span></div>
<h1>{{ $profile['name'] }}</h1><p class="headline">{{ $profile['resume_headline'] ?: $profile['headline'] }}</p>
<div class="contact">{{ $profile['location'] }} @if($profile['email']) | <a href="mailto:{{ $profile['email'] }}">{{ $profile['email'] }}</a>@endif<br>
@if($profile['linkedin_url'])<a href="{{ $profile['linkedin_url'] }}">{{ preg_replace('#^https?://(www\.)?#', '', rtrim($profile['linkedin_url'],'/')) }}</a>@endif
@if($profile['github_url']) | <a href="{{ $profile['github_url'] }}">{{ preg_replace('#^https?://(www\.)?#', '', rtrim($profile['github_url'],'/')) }}</a>@endif</div>
<h2>Professional summary</h2><p class="summary">{{ $profile['resume_summary'] ?: $profile['summary'] }}</p>
<h2>Technical skills</h2>@foreach($skills as $category => $items)<p class="skill"><strong>{{ $category }}:</strong> {{ $items->pluck('name')->join(', ') }}</p>@endforeach
<h2>Professional experience</h2>@foreach($experiences as $experience)<div class="entry"><h3>{{ $experience->role }} | {{ $experience->company }}</h3><p class="meta">{{ $experience->start_date?->format('M Y') }} - {{ $experience->end_date?->format('M Y') ?? 'Present' }}@if($experience->employment_type) | {{ $experience->employment_type }}@endif @if($experience->work_mode) | {{ $experience->work_mode }}@endif</p><p>{!! nl2br(e($experience->description)) !!}</p></div>@endforeach
@if($projects->isNotEmpty())<h2>Selected projects</h2>@foreach($projects as $project)<div class="entry"><h3>{{ $project->title }} <span style="font-size:8pt;font-weight:normal">| {{ implode(', ', $project->tech_stack ?? []) }}</span></h3><p>{{ $project->summary }}</p>@if($project->live_url)<a href="{{ $project->live_url }}">{{ $project->live_url }}</a>@endif</div>@endforeach @endif
@if($profile['education_title'])<h2>Education</h2><div class="entry"><h3>{{ $profile['education_title'] }}</h3><p>{{ $profile['education_institution'] }} | {{ $profile['education_period'] }}</p></div>@endif
</body></html>
