<script setup>
import PortfolioLayout from '@/Layouts/PortfolioLayout.vue';
import ArchitectureScene from '@/Components/Portfolio/ArchitectureScene.vue';
import { Head, Link } from '@inertiajs/vue3';
import { computed } from 'vue';
const props = defineProps({ profile: Object, skills: Object, projects: Array, experiences: Array, certificates: Array, sections: Array, projectCount: Number, experienceDuration: String });
const currentRoles = computed(() => (props.experiences ?? []).filter(item => !item.end_date && item.employment_type !== 'Freelance'));
</script>
<template>
    <Head><title>{{ profile?.name ?? 'Ibrahim Nawab' }} — Laravel & Full Stack Developer</title><meta head-key="description" name="description" :content="profile?.summary"></Head>
    <PortfolioLayout :profile="profile">
        <div class="folio-home">
            <section class="editorial-hero">
                <div class="hero-byline"><span><i></i> {{ profile?.availability || 'Full stack developer' }}</span><span>{{ profile?.location || 'Karachi, Pakistan' }} · Working globally</span></div>
                <div class="hero-title-row"><h1>Engineering<br><span>the <em>next.</em></span></h1><div class="hero-side-note"><span>PORTFOLIO / 2026</span><p>Thoughtful digital experiences.<br>Dependable foundations.</p></div></div>
                <div class="hero-stage"><div class="hero-statement"><span class="folio-label">HELLO, I’M IBRAHIM NAWAB</span><p>A full stack developer turning ambitious ideas into <strong>products that work.</strong></p><Link href="/work" class="folio-button">Discover my work <span>↗</span></Link></div><ArchitectureScene/><div class="hero-profile"><img v-if="profile?.photo_path" :src="profile.photo_path" :alt="profile.name" width="88" height="104"><span>Laravel. Vue. APIs.<br>Built with purpose.</span><a v-if="profile?.resume_available" href="/resume" class="folio-link">Download resume ↓</a><Link v-else href="/experience" class="folio-link">My experience ↗</Link></div></div>
                <div class="hero-bottom"><span>GOOD SOFTWARE STARTS WITH A GOOD QUESTION.</span><a href="#selected-work">SCROLL TO EXPLORE ↓</a></div>
            </section>
            <section class="current-roles" aria-label="Current companies"><span class="folio-label">CURRENTLY BUILDING WITH</span><span v-for="item in currentRoles" :key="item.id"><strong>{{ item.company }}</strong><small>{{ item.role }}</small></span></section>
            <section id="selected-work" class="folio-section"><header class="folio-section-heading"><span class="folio-label">01 / SELECTED WORK</span><h2>Less noise.<br><em>More impact.</em></h2><div><p>Web platforms, mobile experiences and the systems behind them.</p><Link href="/work" class="folio-link">Explore all {{ projectCount }} projects ↗</Link></div></header>
                <div class="editorial-projects"><Link v-for="(project,index) in projects" :key="project.id" :href="`/work/${project.slug}`" class="editorial-project" :class="`work-tone-${index % 3}`"><div class="work-cover"><img v-if="project.image_path" :src="project.image_path" :alt="project.title" loading="lazy"><template v-else><span class="cover-caption">{{ project.category }} / {{ String(index + 1).padStart(2,'0') }}</span><div class="cover-art" aria-hidden="true"><span>{{ project.title }}</span><i></i><i></i><i></i></div><span class="cover-tech">{{ (project.tech_stack ?? []).slice(0,3).join(' + ') }}</span></template><b class="work-arrow-round">↗</b></div><div class="work-caption"><h3>{{ project.title }}</h3><span>{{ project.company || project.category }}</span></div><p>{{ project.summary }}</p></Link></div><p v-if="!projects?.length">Selected projects are being prepared.</p>
            </section>
            <section id="about" class="folio-about folio-section"><span class="folio-label">02 / BEYOND THE CODE</span><div><h2>Technical depth.<br><em>Human perspective.</em></h2><p>{{ profile?.bio }}</p><Link href="/about" class="folio-link">The story so far ↗</Link></div><aside><strong>{{ experienceDuration }}</strong><span>Since my first professional role</span><strong>{{ projectCount }}</strong><span>Projects in this portfolio</span></aside></section>
            <section id="skills" class="folio-section"><header class="folio-section-heading"><span class="folio-label">03 / MY TOOLKIT</span><h2>From first click<br><em>to final query.</em></h2><p>One connected approach to the whole product.</p></header><div class="folio-skills"><article v-for="(items,category,index) in skills" :key="category"><span>0{{ index + 1 }}</span><h3>{{ category }}</h3><p><span v-for="skill in items" :key="skill.id">{{ skill.name }}</span></p></article></div></section>
            <section v-for="section in sections" :key="section.id" class="folio-section custom-section"><span class="folio-label">{{ section.eyebrow }}</span><h2>{{ section.title }}</h2><p>{{ section.body }}</p><a v-if="section.link_url" :href="section.link_url" class="folio-link">{{ section.link_label || 'Read more' }} ↗</a></section>
            <section v-if="certificates?.length" id="certificates" class="folio-section"><header class="folio-section-heading"><span class="folio-label">04 / ALWAYS LEARNING</span><h2>A foundation.<br><em>Never a finish line.</em></h2></header><div class="folio-certificates"><article v-for="certificate in certificates" :key="certificate.id"><h3>{{ certificate.title }}</h3><span>{{ certificate.issuer }}</span><a v-if="certificate.credential_url" :href="certificate.credential_url" target="_blank" rel="noreferrer" class="folio-link">View credential ↗</a></article></div></section>
            <section class="folio-contact"><span class="folio-label">YOUR NEXT CHAPTER STARTS HERE</span><h2>Have a good<br><em>challenge?</em><span>↗</span></h2><div><Link href="/contact" class="folio-button">Let’s build something <span>↗</span></Link><a v-if="profile?.email" :href="`mailto:${profile.email}`">{{ profile.email }}</a></div></section>
        </div>
    </PortfolioLayout>
</template>
